### PR TITLE
weekly onsen

### PR DESCRIPTION
**Pull request by patidarmanoj10**

### CODE REVIEW

**Review by kevinbeauregard — APPROVED** [review]
Confirmed data locally with these params. 

how was total rewards derived?

**Comment by patidarmanoj10** [comment]
@kevinbeauregard npm run snapshot -- -s 12466698 -e 12511800

This week rewards is 12600/-

**Comment by kevinbeauregard** [comment]
@patidarmanoj10 yep results confirmed

**Review by rokso — APPROVED** [review]

**Comment by rokso** [comment]
Verified and approved

**Pull request merged**
